const images = new Map();

const loadImages = () => {
  images.clear();
  images.set('enemyCrab', imgFromB64('//////LyLy//MiP/IiIiIv8yI//y8i8vL///8vI/8y8')); // 8x8
  images.set('enemyGhost', imgFromB64('9/d/f3/3f/d3d3d393d3f/93d///93////d/f///d/8')); // 8x8
  images.set('enemyKobold', imgFromB64('//RP///0T//zMAM/MzMzM08zM/RPAAD0/zMz//9P9P8')); // 8x8
  images.set('enemyOctopus', imgFromB64('//Iv/y8iIvIvYibyPyIi8/MiIj8vL/Ly/y/y//L//y8')); // 8x8
  images.set('enemyRat', imgFromB64('//MzP/8///P////zf/f3d3d393fyJ/d3N393d///f/c')); // 8x8
  images.set('enemySkeleton', imgFromB64('//d////3f//1dVdfX1d19X/3f/d/V3X3/3/3//9/9/8')); // 8x8
  images.set('enemySnake', imgFromB64('9kRG/0JCRG9kRPRP//9Eb2RGRvRE///0ZERERvZGRG8')); // 8x8
  images.set('enemyWolf', imgFromB64('9vb///d3/29mZ//3d2f/9/d3Zn/3d2Z293d3d/9///c')); // 8x8
  images.set('itemAxe', imgFromB64('//V39//3Xy//9/L3//8vV//y93X/L///8v///y////8')); // 8x8
  images.set('itemChest', imgFromB64('9mZmb2ImYiZiJmImYiZiJmZiJmZiJmImYiIiJmZmZmY')); // 8x8
  images.set('itemCoins', imgFromB64('9v///2Bv///2//9v///2Bv///2//9v///2Bv///2//8')); // 8x8
  images.set('itemDagger', imgFromB64('//////////////f///9///L3////L///8vL///////8')); // 8x8
  images.set('itemPotionLarge', imgFromB64('/1VV///1X///9V///1VV//VSJV/1IiJf9SIiX/9VVf8')); // 8x8
  images.set('itemPotionSmall', imgFromB64('/1VV///1X///9V///1VV//VVVV/1VVVf9SIiX/9VVf8')); // 8x8
  images.set('itemShieldLarge', imgFromB64('ERERERd3VVEXd1VRF3dVURd3VVHxd1Uf/xdR///xH/8')); // 8x8
  images.set('itemShieldSmall', imgFromB64('//////ERER/xd1Uf8XdVH/F3VR//F1H///Ef//////8')); // 8x8
  images.set('itemSword', imgFromB64('////9////3////f///9///L3////L///8vL//y////8')); // 8x8
  images.set('layoutEmpty', imgFromB64('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')); // 8x8
  images.set('layoutFloor', imgFromB64('AAAAAAAAAAAAEAAAAAAAAAAAABAAAAAAAAAQAAAAAAA')); // 8x8
  images.set('layoutWall', imgFromB64('AAAAABEQEREREBERAAAAAAEREREAAAAAEREBERERARE')); // 8x8
  images.set('player', imgFromB64('//M////zP//0QzRPRERERE9URfQ/RETz/1/1//9f9f8')); // 8x8
  images.set('screenStaticGameOver', imgFromB64('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIiAgAiIiIiAAIgAAIgAAACIiAgAAAAAAAAAAAAAAACIAIiAAAiAiAAIiIiIiIAACIAIgAAAAAAAAAAAAAAACIAACAAAiACIAIiAiIgIiACIAAAAAAAAAAAAAAAAAAAIgAAAAAiAAIgAiAAIgACIAIgAAIAAAAAAAAAAAAAAAAiAAAiACIAIiACIAAiAAIgAiIiIAAAAAAAAAAAAAAAACIAIiIAIiICIAIgACIAAiACIAAgAAAAAAAAAAAAAAAAIgAAIgACIAIgACIAIgAiAAIgAAAAAAAAAAAAAAAAAAAiIAAiAAIgAiAAIgAiACIAACIAAiAAAAAAAAAAAAAAAAIiIiIAIgAAIAIgAiIgAiAAAiIiAAAAAAAAAAAAAAAAAAACIAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGd3d3dgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZ3d3d3d3d2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHd3d3d3d3d3d3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGd3d3d3d3d3d3dgAAAAAAAAAAAAAAAAAAAAAAAAAAAHd3d3d3d3d3d3d3cAAAAAAAAAAAAAAAAAAAAAAAAAAGd3d3d3d3d3d3d3d2AAAAAAAAAAAAAAAAAAAAAAAAAHd3d3d3d3d3d3d3d3dwAAAAAAAAAAAAAAAAAAAAAAAGd3d3d3d3d3d3d3d3d3YAAAAAAAAAAAAAAAAAAAAAAAd3d3d3d3d3d3d3d3d3dwAAAAAAAAAAAAAAAAAAAAAAZ3d3d3d3d3d3d3d3d3d3YAAAAAAAAAAAAAAAAAAAAAB3d3d3d3d3d3d3d3d3d3dwAAAAAAAAAAAAAAAAAAAAAHd3d3d3d3d3d3d3d3d3d3AAAAAAAAAAAAAAAAAAAAAGd3d3d3d3d3d3d3d3d3d3dgAAAAAAAAAAAAAAAAAAAAd3d3d3d3d3d3d3d3d3d3d3AAAAAAAAAAAAAAAAAAAAB3d3d3d3d3d3d3d3d3d3d3cAAAAAAAAAAAAAAAAAAAAHd3d3d3d3d3d3d3d3d3d3dwAAAAAAAAAAAAAAAAAAAAd3d3cAAHd3d3d3cAAHd3d3AAAAAAAAAAAAAAAAAAAAB3d3cAAAAAd3dwAAAAB3d3cAAAAAAAAAAAAAAAAAAAAGd3dwAAAAAHdwAAAAAHd3dgAAAAAAAAAAAAAAAAAAAAB3dwAAAAAAd3AAAAAAB3dwAAAAAAAAAAAAAAAAAAAAAHd3AABVAAd3dwAFUAAHd3AAAAAAAAAAAAAAAAAAAAAAZ3cAAFUAB3d3AAVQAAd3YAAAAAAAAAAAAAAAAAAAAAAHdwAAAAB3d3dwAAAAB3cAAAAAAAAAAAAAAAAAAAAAAAd3AAAAB3cHB3cAAAAHdwAAAAAAAAAAAAAAAAAAAAAAB3dgAABndwAHd2AAAGd3AAAAAAAAAAAAAAAAAAAAAAAHd3YAZ3d3AAd3d2AGd3cAAAAAAAAAAAAAAAAAAAAAAAd3d3d3d3AAAHd3d3d3dwAAAAAAAAAAAAAAAAAAAAAAB3d3d3d3cAAAd3d3d3d3AAAAAAAAAAAAAAAAAAAAAAAGd3d3d3dwAAB3d3d3d3YAAAAAAAAAAAAAAAAAAAAAAAB3d3d3d3B3cHd3d3d3cAAAAAAAAAAAAAAAAAAAAAAAAAZ3d3d3d3d3d3d3d3YAAAAAAAAAAAAAAAAAAAAAAAAAAHd3d3d3d3d3d3d3cAAAAAAAAAAAAAAAAAAAAAAAAAAAAABnd3d3d3d3YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAd3d3d3d3cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwcHcHcHBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwdwdwcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIiAAIiAAIiAAAiIgIAICIiIAAAAAAAAAAAAAAAAAACAAIgACIAIAIAAiACIAACIAAiAAAAAAAAAAAAAAAAACIAACIAIiAAIgAiAAAAAAIgACIAAAAAAAAAAAAAAAAAIgIAIgACIAAgACIAACAAAiACIAAAAAAAAAAAAAAAAAAiAiAiAAIiAiAAIiIiAAACICIAAAAAAAAAAAAAAAAAACIAICIAACICAAAiAAIAAAIiIgAAAAAAAAAAAAAAAAAAIgAAIgAAIiIAACIAAAAAAiACIAIAAAAAAAAAAAAAAAACIAAgAAACIAAAAiAAIgACIAAiIAAAAAAAAAAAAAAAAAAiIgAAAAIgAAAAIiIgACIiIAIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')); // 64x64
  images.set('screenStaticStatus', imgFromB64('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIiIiIiIiIiIiIiIiIiIiIgAGBgYGBgYGBgYGBgAAAAAiIiIiIiIiIiIiIiIiIiIiAAAAAAAAAAAAAAAAAAAAACJiImZiYmJmYmIiIiIiIiIABgAAAAAAAAAAAAYAAAAAImIiYiJiYmIiYiIiIiIiIgAAAAAAAAAAAAAAAAAAAAAiYiJmImJiZiJiIiIiIiIiAAYAAAAAAAAAAAAGAAAAACJiImIiYmJiImIiIiIiIiIAAAAAAAAAAAAAAAAAAAAAImZiZmImImZiZmIiIiIiIgAGAAAAAAAAAAAABgAAAAAiIiIiIiIiIiIiIiIiIiIiAAAAAAAAAAAAAAAAAAAAACIiIiIiIiIiIiIiIiIiIiIABgAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARERERERERERERERERERERAAYAAAAAAAAAAAAGAAAAABAAAAAAAAAAAAAAAAAAAAEAAGBgYGBgYGBgYGAAAAAAEAAAAAIAAAAAAAAAAAAAAQAGAAAAAAAAAAAABgAAAAAQAAAAIAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAABAAAAIAAAAAAAAABwAAAAEABgAAAAAAAAAAAAYAAAAAEAAgIAAAAAAAAAB3cAAAAQAAAAAAAAAAAAAAAAAAAAAQAAIAAAAAAAAAAAcAAAABAAYAAAAAAAAAAAAGAAAAABAAICAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAEAIAAAAAAAAAAAAAAAAAAQAGAAAAAAAAAAAABgAAAAAQAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAEABgAAAAAAAAAAAAYAAAAAEAREREQAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAQBEQABAAAAAAAAAAAAAABAAYAAAAAAAAAAAAGAAAAABAERAAEAAAAAAAABwAAAAEAAAAAAAAAAAAAAAAAAAAAEAREAAQAAAAAAAB3cAAAAQAGAAAAAAAAAAAABgAAAAAQBEQABAAAAAAAAAcAAAABAAAAAAAAAAAAAAAAAAAAABAARABAAAAAAAAAAAAAAAEABgAAAAAAAAAAAAYAAAAAEAAERAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABAAYAAAAAAAAAAAAGAAAAABAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAEAAAYAAAAAAAAAAAAAAAAQAGAAAAAAAAAAAABgAAAAAQAAZgAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAABAAZgAAAAAAAAAABwAAAAEABgAAAAAAAAAAAAYAAAAAEAZmZmYAAAAAAAB3cAAAAQAAAAAAAAAAAAAAAAAAAAAQAAAGYAAAAAAAAAcAAAABAAYAAAAAAAAAAAAGAAAAABAAAGYAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAEAAAYAAAAAAAAAAAAAAAAQAGAAAAAAAAAAAABgAAAAAQAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAABEREREREREREREREREREREABgAAAAAAAAAAAAYAAAAAEAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABAAYAAAAAAAAAAAAGAAAAABACICIAAAAAAAAHAAAAAAEAAAAAAAAAAAAAAAAAAAAAECIiIiAAAAAAAAcAAAAAAQAGAAAAAAAAAAAABgAAAAAQIiIgIAAAAAAAcAAAAAABAAAAAAAAAAAAAAAAAAAAABACIgIAAAAAAAcAAAAAAAEABgAAAAAAAAAAAAYAAAAAEAAiIAAAAAAABwAAAAAAAQAAAAAAAAAAAAAAAAAAAAAQAAIAAAAAAAAAAAAAAAABAAYAAAAAAAAAAAAGAAAAABAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAEREREREREREREREREREREQAGAAAAAAAAAAAABgAAAAAQAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAABAAZmAAAAAAAAAAAAAAAAEABgAAAAAAAAAAAAYAAAAAEAYABgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAQYGZgYAAAAAAAAAAAAAABAAYAAAAAAAAAAAAGAAAAABBgZmBgAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAEGBmYGAAAAAAAAAAAAAAAQAGAAAAAAAAAAAABgAAAAAQBgAGAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAABAAZmAAAAAAAAAAAAAAAAEABgAAAAAAAAAAAAYAAAAAEAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAARERERERERERERERERERERAAYGBgYGBgYGBgYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')); // 64x64
  images.set('stepsDown', imgFromB64('AAAAAAAAAAAAAAAAVQAAAFUFUABVBVBVVQVQVVUFUFU')); // 8x8
  images.set('stepsUp', imgFromB64('AAAAAAAAAFUABVBVVQVQVVUFUABVAABVAAVVVVVVVVU')); // 8x8
  images.set('uiItemBezel', imgFromB64('Ii8iIvIiL//////yL//////y////////L//////yL//////yL//////yL//////y////////L//////yL//////yIi8iIvIi')); // 12x12
}

const imgFromB64 = (b64) => {
  const padCount = Math.ceil(b64.length / 4) * 4;
  const padded = b64.padEnd(padCount, '=');
  const binStr = atob(padded);
  const img = [];
  for (let i = 0; i < binStr.length; i++) {
    const byte = binStr.charCodeAt(i);
    let pix1 = (byte >> 4) & 0b00001111;
    let pix2 = byte & 0b00001111;
    img.push(pix1 === 15 ? -1 : pix1, pix2 === 15 ? -1 : pix2);
  }
  return img;
}
