import { directions } from './enums.js';

export const levelData = new Map([
  ['Inside', {
    tilemap: [
      [ 1, 2, 2, 2, 2, 2, 2, 3, 2, 4],
      [ 5, 6, 6, 6, 6, 6, 7, 8, 9,10],
      [ 5,11, 6,11, 6, 6, 7, 7, 9,10],
      [ 5,12, 6,12, 6, 6, 7, 7, 7,10],
      [ 5, 6, 6, 6, 6, 6, 7, 7,13,10],
      [ 5, 7, 7, 7, 7, 7, 7,14,15,10],
      [ 5,16,16, 7, 7, 7, 7, 7,13,10],
      [17,18,18,18,20,21,18,18,18,19],
    ],
    exits: [{x: 5, y: 8, target: {ref: 'Outside', x: 5, y: 4.5}}],
  }],
  ['Outside', {
    tilemap: [
      [25,24,25,24,25,24,25,24,25,24],
      [23,26,27,27,27,27,27,27,27,22],
      [25,26,27,28,28,28,28,28,27,24],
      [23,26,27,28,30,30,30,28,27,22],
      [25,26,27,28,31,32,31,28,27,24],
      [23,26,27,28,28,29,28,28,27,22],
      [25,26,27,27,27,29,27,27,27,24],
      [23,26,26,29,29,29,29,29,26,22],
      [25,26,26,26,26,26,26,26,26,24],
      [23,22,23,22,23,22,23,22,23,22],
    ],
    exits: [{ x: 5.5, y: 4.5, target: {ref: 'Inside', x: 4.5, y: 6.5}}],
  }],
]);

const playerU0Image = imageFromB64String('////AA////////AAAP//////8DMzD/////ADAAAwD///AwAjMgAw//8DAiMyIDD//wMCAjIgMP//AgAiMiAg///wACIiAA////AgIiAgIP//AyAiAiAg//8DAgAiMgD///AjMzMiD///8AIiIgAP///wAAAAMwD///8AAAAAD/8');
const playerU1Image = imageFromB64String('////8AD///////8AAA//////8DMzD/////ADAAAwD///AwAjMgAw//8DAiMyIDD//wMCIyAgMP//AgIjIgAg///wACIiAA///wICAiICD///AgIgIgIw//8AIyIAIDD///AiMzMyD///8AAiIiAP//8AMwAAAA////AAAAAA//8');
const playerD0Image = imageFromB64String('////AAAP//////AiMyD////wAiIAIA///wMCMzMAMP//AwMAADAw//8DAAAAADD//wIgAAACIP//8DMDMDMP///wIwMwMg///wICMzMgIP//AgAAAAAjD/8CMwIiIAMP//AzAzMyAP///wAiIAAP///wAAADMgD///8AAAAAD/8');
const playerD1Image = imageFromB64String('///wAAD//////wIzIg/////wAgAiIA///wMAMzMgMP//AwMAADAw//8DAAAAADD//wIgAAACIP//8DMDMDMP///wIwMwMg///wICMzMgIP/wMgAAAAAg//AwAiIgMyD//wAjMzAzD///8AACIgD///8AIzAAAA////AAAAAA//8');
const playerL0Image = imageFromB64String('////AAAP/////wAjIiD////wMwIzIg//8AAjMCICIP//AAIzADAiD///AAICMCIP/wAwMAMwIP//AzAzAzAP///wIzMDIP////8CIgIA/////wAAACD/////AgMwIg////8DAzAiD////wIAAAAP////AAMzMP////AAAAAAD/8');
const playerL1Image = imageFromB64String('//////////////8AAAD///8PACMyIgD//wAzAiMyIg//ACMwIgIiD//wAjMAMCIP//8AAgIwIP//ADAwAzAg//8DMDMDMA////AjMwMg/////wAAAAD/////8DMCIA/////wMwIgMP///wAAIgAw///wMzMAAzD///AAAAAAAA8');
const playerR0Image = imageFromB64String('///wAAD//////wIiMgD////wIjMgMw///wIgIgMyAA/wIgMAMyAA//AiAyAgAP///wIDMAMDAP//8AMwMwMw////AjAzMg////8AICIg/////wIAAAD////wIgMwIP////AiAzAw////8AAAACD/////AzMwAP////AAAAAAD/8');
const playerR1Image = imageFromB64String('/////////////wAAAP////8AIiMyAPD/8CIjMiAzAP/wIiAiAzIA//AiAwAzIA///wIDICAA////AgMwAwMA///wAzAzAzD///8CMDMyD////wAAAAD////wAiAzD////wMCIDMP////AwAiAAD///8DMAAzMw//8AAAAAAAD/8');
export const playerAnimations = new Map([
  [directions.up,    new Anim([playerU0Image, playerU1Image], 10, true)],
  [directions.down,  new Anim([playerD0Image, playerD1Image], 10, true)],
  [directions.left,  new Anim([playerL0Image, playerL1Image], 10, true)],
  [directions.right, new Anim([playerR0Image, playerR1Image], 10, true)],
]);

export const tileImages = new Map([
  [ 1, imageFromB64String('IiIiIiIiIiIjMzMzMzMzMyMRERERERERIxAAAAAAAAAjEAIiIiIiIiMQICIiIiIiIxAiAiIiIiIjECIgIiIiIiMQIiIAAAAAIxAiIgAiIiIjECIiAgERESMQIiICEBERIxAiIgIRAAAjECIiAhEAESMQIiICEQEAIxAiIgIRAQA')],
  [ 2, imageFromB64String('IiIiIiIiIiIzMzMzMzMzMxERERERERERAAAAAAAAAAAiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIgAAAAAAAAAAIiIgIiIiICIRERAREREQEREREBERERARAAAAAAAAAAAQEREREBEREQAAAAAAAAAAAAAAAAAAAAA')],
  [ 3, imageFromB64String('AAAAAAAAAAADMzMzMzMzMAMzMzMzMzMwAzMzMzMzMzADMzMzMzMzMAAAAAAAAAAAAzMzMzMzMzACAAAAAAAAIAICIiIiIiAgAgIiIAIiICACAiIjMiIgIAIAAAAAAAAgAgIiIiIiICACAiIgAiIgIAICIiMyIiAgAgAAAAAAACA')],
  [ 4, imageFromB64String('IiIiIiIiIiIzMzMzMzMzMhEREREREREyAAAAAAAAATIiIiIiIiABMiIiIiIiAgEyIiIiIiAiATIiIiIiAiIBMgAAAAAiIgEyIiIiACIiATIRERAgIiIBMhERASAiIgEyAAARICIiATIRABEgIiIBMgAQESAiIgEyABARICIiATI')],
  [ 5, imageFromB64String('IxAiIgIRAQAjECIiAhEBACMQIiICEQEAIxAiIgAAAQAjECIiAhEBACMQIiICEQEAIxAiIgIRAAAjECIiAhEBACMQIiICEQEAIxAiIgIRAQAjECIiAhEBACMQIiIAAAEAIxAiIgIRAQAjECIiAhEBACMQIiICEQAAIxAiIgIRAQA')],
  [ 6, imageFromB64String('IjIiMiIjIiIiMzMyIiIyIjIyIjIiIjMzIyIiIyIiMiIjIiIjMzMyIiMyIjIiMiMiMiMzIiIyIjMiIiMiIjIiIyIiIjIiMiIjMiIjIzMzIiMjIjIiMiIzMiIzIiIyIiMiIiMiIjIiIyIiMzIjMyIjMjMiIzIiMzIjIyIiMiIjIiI')],
  [ 7, imageFromB64String('MzMzMzMzMzMzMzMzMzMzMzIjMzMzMzMzMzMzMzMzMzMzMzMzIiMzMzMzMzMzMzMzMzMzMzMzMzMiIiIiIiIiIjMiIzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMyIzMzMzMzMzMzMzMzMzMzMzMzMzMzIiMzMzIiIiIiIiIiI')],
  [ 8, imageFromB64String('AgIiIiIiICACAiIgAiIgIAICIiMyIiAgAgAAAAAAACACAiIiIiIgIAICIiACIiAgAgIiIzIiICACAAAAAAAAIDMiIzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMyIzMzMzMzMzMzMzMzMzMzMzMzMzMzIiMzMzIiIiIiIiIiI')],
  [ 9, imageFromB64String('MAAAAAAAAAMCIiIiIiIiIAEgIiIiIgIQAiIiIiIiIiABEREREREREAIiIiIiIiIgASAiIiIiAhACIiIiIiIiIAEREREREREQAiIiIiIiIiABICIiIiICEAIiIiIiIiIgAAAAAAAAAAABEBEBEBEBEAEQEQEQEQEQMAAAAAAAAAM')],
  [10, imageFromB64String('ABARICIiATIAEBEgIiIBMgAQESAiIgEyABAAACIiATIAEBEgIiIBMgAQESAiIgEyAAARICIiATIAEBEgIiIBMgAQESAiIgEyABARICIiATIAEBEgIiIBMgAQAAAiIgEyABARICIiATIAEBEgIiIBMgAAESAiIgEyABARICIiATI')],
  [11, imageFromB64String('MzMzMzMzMzMyAAAAAAAAIzACERERERADMCEREREREQMwIRAAAAERAzAAAzMzMAADMDMDIiIwMwMwAAAAAAAAAwIzMzMzMzMgAjMzMzMzMyACIiIjMzMyIAIjMzMzMzMgAjMzMzMzMyACMzMzMzMzIAIzMzMzMzMgAjMzMzMzMyA')],
  [12, imageFromB64String('AjMzMzMzMyACMzMzMzMzIAIiIiMzMzIgAiMzMzMzMyACMzMzMzMzIAIzMzMzMzMgAjMzMzMzMyACMzMzMzMzIAIjMzMzMzIgAiIiIiIiIiABIiIiIiIiEAAAAAAAAAAAIBEREREREQIhAAAAAAAAEzMzMzMzMzMzIiIiIiIiIiI')],
  [13, imageFromB64String('MzMzMzMzMzMzMAADMAADMzMCIiACIiAzMCIhEiIRIgMwIhIRESISAzECEiIiIhIDMQISEAEhIAMwIhIiIiEgEzAhIhERIhIDMCEREiIRIgMwAiIgACIgAzAQAAERAAEDMBEREREREQMyAREQABEQIzMgAAIyAAIzMzMzMzMzMzM')],
  [14, imageFromB64String('MzAAAAAAAAAzAiIiIiIiIjAiIiIiIiIiMCIiIiIiIiIwIiIiIiIiIjAiIiIiIiIiMCIiIiIiIiIwIiIiIiIiIjAiIiIiIiIiMDIiIiIiIiIwIyIiIiIiIjASMzMzMzMzMwEREREREREzAAAAAAAAADMBIhARERERMyAAAiIiIiI')],
  [15, imageFromB64String('AAAAAAAAAzMiIiIiIiIgMyIiIiIiIiIDIiIiIiIiIgMiIiIiIiIiAyIiIiIiIiIDIiIiIiIiIgMiIiIiIiIiAyIiIiIiIiIDIiIiIiIiIwMiIiIiIiIyAzMzMzMzMyEDEREREREREDMAAAAAAAAAMxEREREBIhAzIiIiIiAAAjM')],
  [16, imageFromB64String('MzMzAAAzMzMzMwAiIgAzMzMwIiIiIgMzMzAiEREiAzMzAiEAABIgMzACIAAAAiADMAIgAAACIAMwICIAACICAzAgEiIiIQIDMBIAIzIAIQMwEiIAACIhAzASEiIiISEDMwERIzIREDMzAREiIhEQMzMwARIhEAMzMzMwAAADMzM')],
  [17, imageFromB64String('IxAiIgIRAQAjECIiAhEBACMQIiICEQARIxAiIgIRAAAjECIiAhARESMQIiICARERIxAiIgAiIiIjECIiAAAAACMQIiAiIiIiIxAiAiIiIiIjECAiIiIiIiMQAiIiIiIiIxAAAAAAAAAjERERERERESMzMzMzMzMzIiIiIiIiIiI')],
  [18, imageFromB64String('AAAAAAAAAAAAAAAAAAAAABAREREQERERAAAAAAAAAAARERAREREQEREREBERERARIiIgIiIiICIAAAAAAAAAACIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiAAAAAAAAAAARERERERERETMzMzMzMzMzIiIiIiIiIiI')],
  [19, imageFromB64String('ABARICIiATIAEBEgIiIBMhEAESAiIgEyAAARICIiATIREQEgIiIBMhERECAiIgEyIiIiACIiATIAAAAAIiIBMiIiIiICIgEyIiIiIiAiATIiIiIiIgIBMiIiIiIiIAEyAAAAAAAAATIRERERERERMjMzMzMzMzMyIiIiIiIiIiI')],
  [20, imageFromB64String('AAAAAjMzMzMBEiIwMzMzMwESIjAzMzMzASEjMDMzMzMBISMwMzMzMwESIzAzMzMzARIiMDMzMzMBEiIwMzMzMwERIzAzMzMzASEjMDMzMzMBISMwMzMzMwEAADAzMzMzADMzADMzMzMDMRMwMzMzMwMTMTAzMzMzAxMxMDMzMzM')],
  [21, imageFromB64String('MzMzMyAAAAAzMzMzAyIhEDMzMzMDIiEQMzMzMwMyEhAzMzMzAzISEDMzMzMDMiEQMzMzMwMiIRAzMzMzAyIhEDMzMzMDMhEQMzMzMwMyEhAzMzMzAzISEDMzMzMDAAAQMzMzMwAzMwAzMzMzAzETMDMzMzMDEzEwMzMzMwMTMTA')],
  [22, imageFromB64String('MzMzMgAAAAAzMzIAEiIiIjMzABIiIiMzMzASIiEiMzMzASIiESIzMzIBIiERIiMzMBIiEREiIiIgEiIRERIiIgESIhERERIiARIiIREREREBEiIiEREREQESIiIiERERAREiIiIiEREBESIiIiIhEQERESIiIiIiARERESIiIiI')],
  [23, imageFromB64String('AAAAACMzMzMiIRERACMzMyIiESIRADMzMiIhEiIRAzMyIiERIiEQMyIiIRESIRAjIiIhERIiEQMiIhEREiIRAiIhERESIhEQERERESIiERARERESIiIREBEREiIiIhEQEREiIiIiERAREiIiIiERECIiIiIiEREQIiIiIhERERA')],
  [24, imageFromB64String('AREREREiIiIgERERERIiIiARERERERIiAgERERERERECIBEREREREQEiABERERERIAERAAABEREiIAAiIhARETIiAzIiIgERMiAzMiIiIAAzAjMiIQIjMzMCMiIQACMzMwIiEAEQEjMzIAABERECIjMzMiIhERAiMzMzMzMiIgA')],
  [25, imageFromB64String('IiIiERERERAiIiERERERAiIiERERERECERERERERECARERERERECIBERERERACIQEREQAAAREAIREQEiIgACIhEQIiIzICIjAAIiIjMyAiMiIiASIzMgMyIiAAEiMyAzIiEBEAEiIDMiIBEREAACMyIBERIiMzMzACIiMzMzMzM')],
  [26, imageFromB64String('MzMzMzMzMzMzMjMzMzMzMzIyMjMzMzMzMyMjMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMyMzMzMzMzMjIyMzMzMzMzIyMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM')],
  [27, imageFromB64String('MzMzMzMzMzMzMzMzMzMzMzMwAzMzMAMzMwMwMzMDMDMwMiMDMDIjAzAyIwMwMiMDMBMwAzATMAMwMQEDMDEBAzAxIQMwMSEDMDEhAzAxIQMwMyEDMDMhAzAxIQMwMSEDMCEhAzAhIQMwISEDMCEhAzMAADMzAAAzMzMzMzMzMzM')],
  [28, imageFromB64String('IjMyIyIzMiMyIzIzMiMyMzIiMzMyIjMzMyIzMjMiMzIzIjMiMyIzIjMiMiIzIjIiMzIyIzMyMiMzMjIjMzIyIyIzMiMiMzIjMiMyMzIjMjMyIjMzMiIzMzMiMzIzIjMyMyIzIjMiMyIzIjIiMyIyIjMyMiMzMjIjMzIyIzMyMiM')],
  [29, imageFromB64String('MiIiIzIiIiMiIiIiIiIiIiIiEiIiIhIiIiIiIiIiIiIhIiIiISIiIiIiIyIiIiMiIiIiIiIiIiIyIiIjMiIiIzIiIiMyIiIjIiIiIiIiIiIiIhIiIiISIiIiIiIiIiIiISIiIiEiIiIiIiMiIiIjIiIiIiIiIiIiMiIiIzIiIiM')],
  [30, imageFromB64String('IQAAEiEAABIQEiEBEBIhAQEjMhABIzIQASMyEAEjMhABIzIQASMyEAEjMhABIzIQASMiEAEjIhABIzIQASMyEAEjMhABIzIQASMyEAEjMhABIzIQASMyEAEiIhABIiIQARIhEAESIRABEREQAREREBAREQEQEREBIQAAEiEAABI')],
  [31, imageFromB64String('AAAAAAAAAAABEREREREREAMzMzMzMzMwAiIiIiIiIiAAAAAAAAAAAAEQIAAAAgEQAiAgAAACAiACICAAAAICIAIgIAAAAgIgAiAjMzMyAiABEAAAAAACEAESIiIzIiIQAiIRIjMhEiACIhEiIiESIAAAAAAAAAAAIiIiIiIiIiI')],
  [32, imageFromB64String('AAAAAAAAAAAzMzMzMzMzMzMzMzMzMzMzIiIiIiIiIiIiERERERERIiIQAAAAAAEiAAAAAAAAAAAREAAAAAABESIQAAAAAAIhIhAAAAAAAiEiEAAAAAACISIQAAAAAAIhIhAAAAAAAiEiEAAAAAACISIQAAAAAAIhAAAAAAAAAAA')],
]);
